### ISSUE TITLE
ERROR: Could not find valid gem 'csv' (>= 0) in any repository

### ISSUE THREAD

**Issue by joereynolds** [imartingraham/csv-split#2]
I got this error whilst doing a `gem install csv`

```
ERROR: Could not find valid gem 'csv' (>= 0) in any repository
```

It still seems to work regardless of that gem being installed though...

**Comment by imartingraham** [comment]
my mistake, the csv lib is part of ruby. I've updated the README.  Thanks!

**Comment by joereynolds** [comment]
Thanks! 
Can you remove it from the 'Required Gems' section too?

**Comment by imartingraham** [comment]
@joereynolds removed. Thanks for catching that.
